Adding options to install idrac-packages and "all" srvadmin-packages.
vide/puppet-omsa pull request #2
Opened 2016-10-26 11:34 UTC by palsveningson

The idrac-packages is nice to have installed for racadm-usage.
The "all"-option is a nice feature.

2016-10-26 13:57 UTC, vide requested changes
First of all, thanks for your contribution!
Can you remove any RPM mention from the README, since the module targets Debian too?

Thanks!

2016-10-26 14:14 UTC, palsveningson commented
Hi! Good point, I replaced it with packages.

BR!

2016-10-26 14:20 UTC, vide requested changes
Ok, thinking it twice (a part from the other small fixes I commented) I think you should make the `srvadmin-all` package installation mutually exclusive with the other packages, with the current code, dependencies will break if by mistake you have `install_all` and some other install flag activated

2016-10-26 14:20 UTC, vide commented on manifests/install.pp
> +  if ( str2bool("${::omsa::install_idac}")) {
There's a typo here

2016-10-26 14:20 UTC, vide commented on README.md
> + Install the meta package-idrac package. Default: false
I think `Install the idrac meta package` is better

2016-10-27 13:30 UTC, palsveningson commented
Hi! I did some changes. Hope this is what you wanted :)

BR

2016-11-08 10:15 UTC, vide commented
Hello @palsveningson sorry for the delay. In the end I've implemented your proposal with #3 so I'm gonna close this PR and merge the other one. Please checks if it does what you needed!

2016-11-08 10:15 UTC, closed without merging